config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :categories  
  resources :users
  resources :orders
  resources :line_items
  resources :carts, except: [:edit, :update]
  resources :foods
  
  root 'categories#index'

end

app/models/food.rb
class Food < ActiveRecord::Base
  resourcify
  has_many :line_items
  has_many :orders, through: :line_items
  belongs_to :category

  before_destroy :ensure_not_referenced_by_any_line_item

  FOOD_TYPES = ["Starters", "Main Course", "Dessert", "Cold Drinks"]
  validates :category_id, presence: true
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image'
  }

  def self.order_by_title
    Food.order(:title)
  end

  private
	 #ensure there are no line items that reference this food item
  def ensure_not_referenced_by_any_line_item
   if line_items.empty?
     return true
   else
     errors.add(:base, 'Food items present in Line Items')
     return false
   end
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_food


  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    if @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_path, notice: 'Food was successfully destroyed.' }
      
    end
    else
     respond_to do |format|
      format.html { redirect_to foods_path, notice: 'Food cannot be destroyed as an order contains it' }
      
    end
   end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  def invalid_food
    logger.error "Attempt to access invalid food resource #{params[:id]}"
    redirect_to :root, notice: 'Invalid Food Item'
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def food_params
    params.require(:food).permit(:title, :description, :category_id,:image_url, :price)
  end
   
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, Category.all.collect {|c| [c.name, c.id]} ,:prompt => 'Select Category' %>
  </div>
 
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Listing Foods</h1>

<table> 
    <% @foods.each do |food| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <%= image_tag(food.image_url, class: 'list_image') %>
        </td>
        <td class="list_description">
        <dl>
        <dt><%= food.title %></dt>
        <strong><dt>in <%= link_to food.category.name, food.category %></dt></strong>
        <dd><%= truncate(strip_tags(food.description), length: 80) %></dd>
         <dt><%= food.price %></dt>
        </td>      
       <td class="list_actions">
        <%= link_to 'Show', food %><br/>
        <% if can? :manage, food %>
        <%= link_to 'Edit', edit_food_path(food) %><br/>
        <%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </td>
      </tr>
    <% end %>
</table>

<br/>
<% if can? :manage, @food %>
<%= link_to 'New Food', new_food_path %>
<% end %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @food.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>



<p>
  <strong>Image url:</strong>
  <%= @food.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food.price %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>