config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :categories  
  resources :users
  resources :orders
  resources :line_items
  resources :carts, except: [:edit, :update]
  resources :foods
  
  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	resourcify
	has_many :foods
	validates :name, presence: true
  
end

app/controllers/categories_controller.rb
  class CategoriesController < ApplicationController
  include CurrentCart
  before_action :set_cart
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category was successfully destroyed.' }
      
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category %></td>
        <% if can? :manage, category %>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manage, @category %>
<%= link_to 'New Category', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<h2>Foods in <%= @category.name %></h2>

<% unless @category.foods.empty? %>

<table> 
    <% @category.foods.each do |food| %>
      <% cache ['entry', food] do %>
      <div class="entry">
        <%= image_tag(food.image_url) %>
        <h3><%= food.title %></h3>
        <p><%= sanitize(food.description) %></p>
        <div class="price_line">
          <span class="price"><%= number_to_currency(food.price) %></span>
          <%= button_to 'Add to Order', line_items_path(food_id: food), remote: true %>
        </div>
      </div>
      
    <% end %>
    <% end %>
</table>
<% else %>
<h2>No foods to show</h2>
<% end %>
<br/>
<% if can? :manage, @category %>
<%= link_to 'Edit', edit_category_path(@category) %> |
<% end %>
<%= link_to 'Back', categories_path %>