config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :categories  
  resources :users
  resources :orders
  resources :line_items
  resources :carts, except: [:edit, :update]
  resources :foods
  
  root 'categories#index'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  resourcify
  belongs_to :order
  belongs_to :food
  belongs_to :cart

  def total_price
  	food.price * quantity
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  authorize_resource
  before_action :set_cart, only: [:new, :create, :update]

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

 
  # POST /line_items
  # POST /line_items.json
  def create
    food = Food.find(params[:food_id])
    respond_to do |format|
      if @cart.add_food(food.id)
        format.js
        format.html { redirect_to :root }
      else
        format.html { render :new }
      end
    end
  end

 

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_path, notice: 'Line item was successfully destroyed.' }
    end
  end

  private
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def line_item_params
    params.require(:line_item).permit(:food_id)
  end
  
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_id %><br>
    <%= f.text_field :food_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
  <td><%= line_item.quantity %>&times;</td>
  <td><%= line_item.food.title %></td>
  <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/create.js.erb
function initialize() {
  $('#notice').hide();
  $('#cart').show();
  $('#cart').html("<%= escape_javascript render(@cart) %>");
}

$(document).ready(initialize);
$(document).on('page:load', initialize);

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.food.title %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <% if can? :manage, @line_item %>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @line_item.food %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>
<% if can? :manage, @line_item %>
  <%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<% end %>
<%= link_to 'Back', line_items_path %>